--< Module >--
return {
    abs = math.abs;
    acos = math.acos;
    asin = math.asin;
    atan = math.atan;
    atan2 = math.atan2;
    ceil = math.ceil;
    clamp = math.clamp;
    cos = math.cos;
    cosh = math.cosh;
    deg = math.deg;
    exp = math.exp;
    floor = math.floor;
    fmod = math.fmod;
    ldexp = math.ldexp;
    log = math.log;
    max = math.max;
    min = math.min;
    noise = math.noise;
    pow = math.pow;
    rad = math.rad;
    random = math.random;
    sign = math.sign;
    sin = math.sin;
    sinh = math.sinh;
    sqrt = math.sqrt;
    tan = math.tan;
    tanh = math.tanh;
}